#!/bin/bash

# To be run within the VM

set -euo pipefail
IFS=$'\n\t'

# service exists
sudo sh -c "systemctl show hello.service | grep UnitFileState=enabled"

# service is enabled
sudo sh -c "systemctl show hello.service | UnitFilePreset=enabled"

# service is of type simple
grep Type=simple /etc/systemd/system/hello.service
