- name: Version of the deployed binary is registered
  command: "{{ program_location }} --version"
  register: program_version
  tags: [ version, deployment ]

- name: System packages are installed
  apt:
    name:
      - python3-pip
      - python3-setuptools
    state: present
    update_cache: true
  tags: apt, pip, python, influxdb

- name: Python modules are present
  pip:
    name:
    - influxdb
  tags: [ influxdb, python, pip ]

- name: Deployment event info is written
  influxdb_write:
    hostname: "{{ deployment_event_url | urlsplit('hostname') }}"
    ssl: "{% if deployment_event_url[0:5] == 'https' %}true{% else %}false{% endif %}"
    use_udp: false
    udp_port: 4444
    port: "{{ deployment_event_url | urlsplit('port') }}"
    username: "{{ deployment_event_url | urlsplit('username') }}"
    password: "{{ deployment_event_url | urlsplit('password') }}"
    database_name: "{{ deployment_event_url | urlsplit('path') | replace('/', '') }}"
    data_points:
      - measurement: events
        tags:
          host: "{{ inventory_hostname }}"
        fields:
          title: "Deployment of {{ program.name }} {{ program_version.stdout }}"
  tags: [ influxdb, events, deployment ]
