require 'pathname'

Vagrant.configure('2') do |config|
  debian = %w(buster bullseye).map { |b| "debian/#{b}64" }
  ubuntu = %w(bionic focal).map { |b| "ubuntu/#{b}64" }

  Pathname.glob('test-*').product(debian + ubuntu).each do |test_dir, box|
    test_name = test_dir.to_s
    family, flavour = box.split('/')
    vm_name = [test_name, flavour].join('-')

    config.vm.define(vm_name) do |machine|
      machine.vm.box = box
      machine.vm.hostname = vm_name
      machine.vm.network 'private_network', type: 'dhcp'

      machine.vm.provision 'hostname-resolution', type: 'shell' do |script|
        script.env = { DEBIAN_FRONTEND: 'noninteractive' }
        script.inline = 'apt-get update && apt-get --yes install avahi-daemon libnss-mdns'
      end

      machine.vm.provision 'ansible' do |ansible|
        ansible.playbook = (test_dir / 'playbook.yml').to_s
        ansible.galaxy_roles_path = '../..'
        ansible.compatibility_mode = '2.0'

        extra_vars = {}
        extra_vars[:ansible_python_interpreter] = '/usr/bin/python3'
        ansible.extra_vars = extra_vars
      end

      test_script = test_dir / 'run'

      if test_script.exist?
        machine.vm.provision 'test-prereqs', type: 'shell' do |script|
          script.env = { DEBIAN_FRONTEND: 'noninteractive' }
          script.inline = 'apt-get --yes install binutils curl jq'
        end

        machine.vm.provision 'run-tests', type: 'shell', path: test_script.to_s, privileged: false
      end
    end
  end
end
