#!/bin/bash

# To be run within the VM

set -euo pipefail
IFS=$'\n\t'

# service is enabled as a system service
test "$(systemctl is-enabled hello.service)" = enabled

# service is of type oneshot and runs as the dedicated system user
grep '^Type=oneshot$' /etc/systemd/system/hello.service
grep '^User=hello$' /etc/systemd/system/hello.service

# timer is active
test "$(systemctl is-active hello.timer)" = active