#!/bin/bash

# To be run within the VM

set -euo pipefail
IFS=$'\n\t'

# environment variable file is present
test -f /etc/hello.conf

# process is configured to have these entries
pid=$(systemctl show --property MainPID --value hello.service)
sudo strings /proc/"$pid"/environ | grep foo=bar
sudo strings /proc/"$pid"/environ | grep some=thing
