#!/bin/bash

# To be run within the VM

set -euo pipefail
IFS=$'\n\t'

# service is enabled as a system service
test "$(systemctl is-enabled static-web-server.service)" = enabled

# service is of type simple
grep '^Type=simple$' /etc/systemd/system/static-web-server.service

# service runs as the dedicated system user
grep '^User=static-web-server$' /etc/systemd/system/static-web-server.service

# TODO: does not work yet because the binary is in a subdirectory of the archive
# curl --fail localhost:8787